### ISSUE TITLE
It is not possible to mock invocations with default arguments

### ISSUE THREAD

**Issue by genrym** [wix/specs2-jmock#21]
For example the following code:
```scala
trait WithDefault {
  def withDefault(a: String, b: Boolean = true): (String, Boolean)
}

class WithDefaultImpl extends WithDefault {
  override def withDefault(a: String, b: Boolean): (String, Boolean) = {
    println(s"called with b = $b")
    (a, b)
  }
}
```

And the following test which expected to pass:
```scala
class WithDefaultTest extends SpecificationWithJUnit {

  "withDefault" should {

    "be mocked without specifying the default argument" in new Context {
      checking {
        oneOf(obj).withDefault("a") willReturn "a"
      }

      obj.withDefault("a") must_== ("a", true)
    }
  }

  class Context extends Scope with JMock {
    val obj: WithDefault = mock[WithDefault]
  }
}
```

Fails with the following error:
```
unexpected invocation: withDefault.withDefault$default$2()
expectations:
  expected once, never invoked: withDefault.withDefault("a", <false>); returns "a"
what happened before this: nothing!
java.lang.Exception: 
	at org.jmock.api.ExpectationError.unexpected(ExpectationError.java:23)
	at org.jmock.internal.InvocationDispatcher.dispatch(InvocationDispatcher.java:99)
	at org.jmock.Mockery.dispatch(Mockery.java:246)
	at org.jmock.Mockery.access$100(Mockery.java:31)
	at org.jmock.Mockery$MockObject.invoke(Mockery.java:286)
	at org.jmock.internal.InvocationDiverter.invoke(InvocationDiverter.java:27)
	at org.jmock.internal.FakeObjectMethods.invoke(FakeObjectMethods.java:38)
	at org.jmock.lib.concurrent.Synchroniser.synchroniseInvocation(Synchroniser.java:85)
	at org.jmock.lib.concurrent.Synchroniser.access$000(Synchroniser.java:26)
	at org.jmock.lib.concurrent.Synchroniser$1.invoke(Synchroniser.java:77)
	at org.jmock.lib.JavaReflectionImposteriser$1.invoke(JavaReflectionImposteriser.java:33)
	at com.sun.proxy.$Proxy6.withDefault$default$2(Unknown Source)
	at com.wix.wixcode.events.processor.service.WithDefaultTest$$anon$1.$anonfun$new$4(WithDefaultTest.scala:16)
```

**Comment by dkarlinsky** [comment]
Resolved
