### ISSUE TITLE
Mock creation fails when using specs2 3.5

### ISSUE THREAD

**Issue by ittaiz** [wix/specs2-jmock#7]
Hi,
After upgrading to specs2 3.5 mock creation fails with the following stack
```scala
a mock with name myMockName already exists
java.lang.IllegalArgumentException: a mock with name myMockName already exists
	at org.jmock.Mockery.mock(Mockery.java:125)
	at org.jmock.Mockery.mock(Mockery.java:117)
	at com.wixpress.common.specs2.JMock$class.mock(JMock.scala:64)
```

**Comment by nargov** [comment]
This has been solved in specs2 3.6, tested and confirmed.
